# Data Wrangling

In [105]:
import pandas as pd

In [106]:
#import covariate datasets qnd the outcomes. 

cancer_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/cancer_diab_pop.csv'
df_cancer = pd.read_csv(cancer_path)

age_sex_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/age_sex_diab_pop.csv'
df_age_sex = pd.read_csv(age_sex_path)

COPD_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/COPD_diab_pop.csv'
df_COPD = pd.read_csv(COPD_path)

diabetes_cohort_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/diab_pop.csv'
df_diabetes_cohort = pd.read_csv(diabetes_cohort_path)

exposure_drug_prescription_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/exposure_drugs.csv'
df_exp_drug = pd.read_csv(exposure_drug_prescription_path)

fracture_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/fracture_diab_pop.csv'
df_fracture = pd.read_csv(fracture_path)

hypertension_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/hypertension_diab_pop.csv'
df_hypertension = pd.read_csv(hypertension_path)

surgery_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/surgery_diab_pop.csv'
df_surgery = pd.read_csv(surgery_path)

outcome_VTE_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/outcome_VTE.csv'
df_outcome = pd.read_csv(outcome_VTE_path)

#add event date table : outcome_VTE

In [112]:
df_outcome

                 PAT_ID   eventdate
0     10009136008935799  2020-08-01
1     10013876319320574  2019-05-03
2     10028221240002707  2018-08-10
3     10033964981130542  2019-09-13
4     10039013233044176  2019-03-26
...                 ...         ...
2359  29968111979491266  2019-08-06
2360  29971373380433094  2018-07-22
2361  29987427320037846  2019-05-03
2362  29995597307026117  2018-12-02
2363  29997018692944873  2019-05-22

[2364 rows x 2 columns]

In [108]:
df_diabetes_cohort = df_diabetes_cohort.rename(columns={'pat_id': 'PAT_ID'})
df_outcome = df_outcome.rename(columns={'pat_id': 'PAT_ID'})
total_cohort_df = pd.merge(df_diabetes_cohort, df_age_sex, on='PAT_ID', how='inner')
df_diabetes_cohort = total_cohort_df

In [109]:
df_diabetes_cohort['cancer'] = df_diabetes_cohort['PAT_ID'].isin(df_cancer['PAT_ID']).astype(int)
df_diabetes_cohort['COPD'] = df_diabetes_cohort['PAT_ID'].isin(df_COPD['PAT_ID']).astype(int)
df_diabetes_cohort['fracture'] = df_diabetes_cohort['PAT_ID'].isin(df_fracture['PAT_ID']).astype(int)
df_diabetes_cohort['hypertension'] = df_diabetes_cohort['PAT_ID'].isin(df_hypertension['PAT_ID']).astype(int)
df_diabetes_cohort['surgery'] = df_diabetes_cohort['PAT_ID'].isin(df_surgery['PAT_ID']).astype(int)
print(df_diabetes_cohort['cancer'].sum(), df_diabetes_cohort['COPD'].sum(), df_diabetes_cohort['fracture'].sum(), df_diabetes_cohort['hypertension'].sum(), df_diabetes_cohort['surgery'].sum())

1129 416 88 1779 679

In [110]:
counter = 0
for i in df_diabetes_cohort['PAT_ID']:
    # Check if 'pat_id' is in 'PAT_ID' column of df_outcome
    if i in df_outcome['PAT_ID'].values:
        counter += 1
        # Update 'prs_date' in df_diabetes_cohort based on the condition
        df_diabetes_cohort.loc[df_diabetes_cohort['PAT_ID'] == i, 'eventdate outcome'] = df_outcome.loc[df_exp_drug['PAT_ID'] == i, 'eventdate'].values[0]
counter

IndexError: index 0 is out of bounds for axis 0 with size 0

In [111]:
counter = 0
for i in df_diabetes_cohort['PAT_ID']:
    # Check if 'pat_id' is in 'PAT_ID' column of df_exp_drug
    if i in df_exp_drug['PAT_ID'].values:
        counter += 1
        # Update 'prs_date' in df_diabetes_cohort based on the condition
        df_diabetes_cohort.loc[df_diabetes_cohort['PAT_ID'] == i, 'prs_date'] = df_exp_drug.loc[df_exp_drug['PAT_ID'] == i, 'prs_date'].values[0]
counter

6728

In [99]:
df_diabetes_cohort

,PAT_ID,diab_date,PAT_SEX_COD,age,cancer,COPD,fracture,hypertension,surgery,prs_date
0,10000008910752101,2018-03-06,1,21724,0,0,0,0,0,2019-06-29
1,10001443446743793,2018-09-17,1,27184,0,0,0,0,0,2018-09-17
2,10003741345221536,2018-05-16,1,18063,0,0,0,1,0,2020-01-05
3,10009136008935799,2018-05-07,1,22959,0,0,0,0,0,2020-03-21
4,10011180510471332,2018-08-29,1,27582,0,0,0,0,0,2020-02-12
...,...,...,...,...,...,...,...,...,...,...
8054,29987427320037846,2018-07-22,1,26839,1,0,0,0,0,2018-04-18
8055,29995168593291644,2018-05-09,2,24478,0,1,0,1,0,2018-12-02
8056,29995597307026117,2018-04-18,1,25235,1,0,0,1,0,2019-09-13
8057,29997018692944873,2018-06-24,1,30106,0,0,0,1,0,2019-06-10
8058,29998480270207338,2018-07-03,1,28464,0,0,0,0,0,2018-05-07

In [100]:
#export latest csv file
csv_file_path = '/Users/alecstear/Documents/GitHub/anti-diabetics-study-with-EHR/data tables/df_diabetes_cohort.csv'
df_diabetes_cohort.to_csv(csv_file_path, index=False)